### ISSUE TITLE
string[] can't be serialized like int[] - Feedback for ersioned_docs/version-1.0.0/advanced-topics/serialization/serialization-arrays.md

### ISSUE THREAD

**Issue by 22tooty2** [Unity-Technologies/com.unity.multiplayer.docs#471]
Serializing an int[] and sending it over an Rpc works, but when trying to do that with a string[] i get an error:

Assets\rpc.cs(69,50): error  - Don't know how to serialize String[] - implement INetworkSerializable or add an extension method for FastBufferWriter.WriteValueSafe to define serialization.

sending a normal string works.

here is my code:
`
    [SerializeField]public string[] Names; // also tried without the [SerializeField], didn't work

    void Update()
    {
        if (!NetworkManager.Singleton.IsHost)
        {
            if (Input.GetKeyDown(KeyCode.P))
            {
                PingServerRpc("hello, world"); // Client -> Server
            }
        }
        else
        {
            if (Input.GetKeyDown(KeyCode.L))
            {
                PingClientRpc(Names); // Server -> Client
            }
        }
    }

    [ServerRpc(RequireOwnership = false)]
    private void PingServerRpc(string sometext) { Debug.Log(sometext); }

    [ClientRpc]
    private void PingClientRpc(string[] names) { names = Names; }
`

**Comment by Briancoughlin** [comment]
@LukeStampfli  should this be moved to dev?

**Comment by leissler** [comment]
Just to be clear here. An int[] array does not work in 1.0.0, when using it as type of a NetworkVariable, although stated otherwise in the documentation [here](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/serialization/inetworkserializable#example-array).

Trying that array example leads to an error
----
"The type 'MyCustomStruct' must be a valid unmanaged type (simple numeric, 'bool', 'char', 'void', enumeration type, or struct type with all fields of unmanaged types at any level of nesting) to use it as type argument for 'T' parameter.
----
when trying to use the struct in a NetworkVariable.

**Comment by NoelStephensUnity** [comment]
Hello @leissler!
Yes indeed that documentation was out of date and has since been audited that resulted in a pending updated.  Unfortunately, the pending change is...well still pending.  However, you [can view the pending updated documentation here.](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/81e8894e41f3f3321d768b96061f09328cd92809/docs/advanced-topics/serialization/inetworkserializable.md).
_Of course, the callout dialogs aren't going to display with all of the fancy outlines and such, but it will provide you with some better examples that will compile as well as additional information regarding the limits._

Apologies for the delay in the updated documentation, we hope to have [all of the pending audit udpates](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pulls) merged soon!  😃 

Cheers,

Noel

**Comment by leissler** [comment]
Hi,
thanks for the quick answer and clarification. This drove me nuts while trying.
Maybe it wouldn't be a bad idea for Unity to provide a couple of custom NetworkVariableBase-derived types for common arrays to be serialized in that context. Or maybe even a generic one for Lists, if that's possible.

**Comment by s-omeilia-unity** [comment]
Addressed with PR #675 , pushing to live now

**Comment by NoelStephensUnity** [comment]
@leissler 
It looks like several audit updates went live today.
[INetworkSerializable](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/serialization/inetworkserializable)

**Speaking of additional examples:**
[Arrays ](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/serialization/arrays) was updated as well.
[NetworkVariable](https://docs-multiplayer.unity3d.com/netcode/current/basics/networkvariable) was updated 2 days ago and has additional new examples (that compile).

_I would be very much interested in your feedback if you feel that any of these updates improve your experience while you are becoming familiar with the SDK?_

**Comment by leissler** [comment]
Yes, these updates made the whole documentation much clearer and makes the constraints on NetworkVariale vs. serialization in RPCs more understandable. 
I do think the NetworkList<> class deserves its own chapter with its own examples, as for now it is just mentioned in the NetworkVariable chapter and developers more or less discover it by chance. I think it's a concept that developers should be explicitly made aware of.
